### PR TITLE
rewrite: css-canvas-medical

### PR DESCRIPTION
**Pull request by joseph-bravo**
any comments about class usage would be appreciated :)

127 0 0 1_5500_css-canvas-medical_index html (4)

### CODE REVIEW

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Hey dude! You should make your class names a bit more descriptive, I think the abbreviations are obscuring their purpose. For instance, `fc-gray`, `pv-3`, `m-desc-right`, etc. Rather than single letters, it's worth it to put a full word so your meaning can't be misinterpreted.

**Comment by joseph-bravo** [comment]
127 0 0 1_5500_css-canvas-medical_index html (8)

**Comment by joseph-bravo** [comment]
ew wait not that

**Comment by joseph-bravo** [comment]
127 0 0 1_5500_css-canvas-medical_index html (9)

**Review by codingcodymiller — APPROVED** [review]
Excellent work, man 👏 👏

**Pull request merged**
